### ISSUE TITLE
Does not copy resource files being used/doesn't serve all files in directory

### ISSUE THREAD

**Issue by Zireael07** [hajimehoshi/wasmserve#10]
In a project that is laid out like:
```
/src
    /main.go
    /fonts
       /terminal_16_16.png

```
all that wasmserve serves is the main go. The fonts folder, even though it's in the SAME folder (/src), is not served.

Ref: https://github.com/hajimehoshi/ebiten/issues/1141

**Comment by hajimehoshi** [comment]
`wasmserve` should serve such files. I'll take a look this later.
