### ISSUE TITLE
Build to static files

### ISSUE THREAD

**Issue by Gelio** [hajimehoshi/wasmserve#12]
Hey,

I began experimenting with wasmserve and it helped me get up and going when using https://github.com/hexops/vecty. I built a simple application that I would want to serve publicly now, but I am wondering how one would build the package into a set of static files, as opposed to serving them using wasmserve.

Do you think it would be a good idea to add a build command to wasmserve?

I imagine it would generate files that are otherwise created dynamically in `handle`:
* `index.html`
* `wasm_exec.js`
* `main.wasm`

and put them into an output directory.

This way, one could do e.g.:

```sh
$ wasmbuild -o dist
$ cd dist
$ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
```

or do anything one would want with the `dist` directory (including serving it using GitHub Pages).

I could try to add it if you would like. As far as I know, that would require moving the existing `main.go` into `cmd/wasmserve` and adding another `cmd/wasmbuild`.

**Comment by hajimehoshi** [comment]
Hi,

Thank you for your suggestion but I'm not sure what was the benefit. As you have the set of the static files, just serving them with a file server sounds enough.

**Comment by Gelio** [comment]
Thanks for the quick response. The idea I am trying to convey is to only build the files that are built dynamically by `wasmserve` (`index.html`, `wasm_exec.js`, `main.wasm`). In essence, extract the dynamic generation of those resources and do them once, so they can be served statically later, removing the need for using `wasmserve` in production

**Comment by hajimehoshi** [comment]
I see. As `index.html` and `wasm_exec.js` are not dynamically changed and always same for any Wasm applications, I'm skeptical that it'd be worth providing a command to just output these files.

**Comment by Gelio** [comment]
Sure, maybe you're right. I am new to the ecosystem, and maybe I am still missing something. Do you have any suggestions on how one would easily compile and prepare the project to be served statically?

**Comment by hajimehoshi** [comment]
https://ebiten.org/documents/webassembly.html#Option_2._Compiling_by_yourself This instruction should work even without Ebiten.

**Comment by Gelio** [comment]
Thanks! That's what I was looking for.

I still believe it would be beneficial to combine those 3 manual steps into 1 command 🙂 If you disagree and do not see a point in such a command, feel free to close the issue

**Comment by hajimehoshi** [comment]
This might be useful but I think this is not a target of wasmserve. Let me close this.
