### ISSUE TITLE
allow server-side trigger refresh

### ISSUE THREAD

**Issue by avivey** [hajimehoshi/wasmserve#15]
The feature I want is to allow the server to trigger a reload in the browser. Basically save me the trouble of switching over to the browser and hitting "refresh" manually.

I've seen this done on document-save for some html generator, and it's kinda fun.  They just watch the filesystem, but for wasmserve I think a better approach is to implement a "magic" uri on the server, so when calling it will trigger the reload in all pending browsers.

I think the simplest approach is long-poll from the browser.

**Comment by hajimehoshi** [comment]
Hi,

Probably watching appropriate file sets by `go list` would work. I'm not familiar with watching filesystem, but I'm not sure this worked in the case when a Go file is added and this changes the compile result.

I'll do when I have bandwidth, but contributions are always welcome.

**Comment by avivey** [comment]
This was actually easier then I expected :)

I didn't include watching the filesystem, because I don't think it's really right for go. 

The way I use it is this:
- I have a shell script that watches the filesystem for changes (with `inotifywait`).
- This runs `./build.sh` for any change
- `./build.sh` builds and runs tests, and only if they pass, trigger a reload in wasmserve.

**Comment by hajimehoshi** [comment]
Yeah, I agree watching a file system for Go build system would be pretty difficult, and just offering a URL just to reload seems reasonable. Thank you for your PR!
