### ISSUE TITLE
Function names are missing from profiling tools

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/wasmserve#28]
~b21a8e4a23f15a395faad792d00e8c91355cf49e was the culprit.~

/CC @superloach

**Comment by hajimehoshi** [comment]
Current situation:

![image](https://user-images.githubusercontent.com/16950/189541795-c00cd375-d5a9-4458-8f50-f31a6a20d4b4.png)

**Comment by hajimehoshi** [comment]
~The minimum 'fix' for this bug is like this:~

```diff
diff --git a/main.go b/main.go
index 9d43f83..fd3a5fc 100644
--- a/main.go
+++ b/main.go
@@ -48,7 +48,7 @@ const indexHTML = `<!DOCTYPE html>
     const go = new Go();
     const result = await WebAssembly.instantiate(src, go.importObject);
     go.argv = {{.Argv}};
-    go.env = {{.Env}};
+    //go.env = {{.Env}};
     go.run(result.instance);
   }
   const reload = await fetch('_wait');
```

~But I am not sure why.~

EDIT: Sorry this was not a fix!

**Comment by hajimehoshi** [comment]
The true culprit was 96560b201bd49048fc9f1322c85aec4e3c391b57

**Comment by hajimehoshi** [comment]
When building a binary with `go run -exec=cp`, symbols might be ommitted?

**Comment by hajimehoshi** [comment]
A solution I come up with is to use a temporary directory, a temporary go.mod with the specified version, and go build...

**Comment by hajimehoshi** [comment]
```
$ cat main.go
package main

func main() {
        Foo()
}

func Foo() {
        panic("end")
}

$ GOOS=js GOARCH=wasm go run -exec=cp main.go foo.wasm

$ $(go env GOROOT)/misc/wasm/go_js_wasm_exec foo.wasm 
panic: end

goroutine 1 [running]:
main.Foo(...)
        /Users/hajimehoshi/test/wasm/main.go:8
main.main()
        /Users/hajimehoshi/test/wasm/main.go:4 +0x4
```

Panic messages were shown with symbols.

**Comment by superloach** [comment]
I see... I'll be able to work on this tonight, but I don't get off work until late. Good catch!

**Comment by hajimehoshi** [comment]
I'll take a look now
