### ISSUE TITLE
Default index.html adds extra spacing at top of page?

### ISSUE THREAD

**Issue by emidoots** [hajimehoshi/wasmserve#3]
On the left is `wasmserve`, on the right is `gopherjs`, running otherwise basically identical code. Notice the extra padding wasmserve adds to the top of page:

![image](https://user-images.githubusercontent.com/3173176/51437024-1d3f5b00-1c55-11e9-8bf3-e26490adeb52.png)

I believe this is due to wasmserve not including `<html>`, `<head>` and `<body>` tags properly.

gopherjs serve page:

```html
<html><head><meta charset="utf-8"><script src="..js"></script></head><body></body></html>
```

wasmserve page:

![image](https://user-images.githubusercontent.com/3173176/51437161-7b6d3d80-1c57-11e9-8620-0d0f6204d13f.png)

I did not have time to test in a smaller repro case yet, I will try to do that next.

**Comment by hajimehoshi** [comment]
Hi, thank you for reporting!

> `I believe this is due to wasmserve not including <html>, <head> and <body> tags properly.`

As far as I understand, those tags are optional in HTML5. The DOM trees should be same?

**Comment by hajimehoshi** [comment]
The possible cause is the existence of new line chars.

**Comment by emidoots** [comment]
Ah, you are right.

**Comment by hajimehoshi** [comment]
I removed the suspicious new line. Could you try this again?

**Comment by emidoots** [comment]
Apologies but I think this is actually a problem my code has caused with some sort of browser race condition under GopherJS. I realize now that margin comes from the `h1` element I have in my page but it is _only_ being rendered by the browser properly under wasmserve, and not under `gopherjs serve`. I suspect this to be due to the different execution models of GopherJS and wasm, but am not positive yet. It is definitely a browser bug and not wasmserve's fault, though.
