### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by delaneyj** [hajimehoshi/wasmserve#30]
```go
wasmserve -tags=example github.com/hajimehoshi/wasmserve/example
2023/05/03 14:25:12 go: creating new go.mod: module foo
2023/05/03 14:25:12 go: added github.com/hajimehoshi/wasmserve v0.0.0-20221128151022-689d7ac772c6
2023/05/03 14:25:12 go build -tags example -o /tmp/2838126562/main.wasm github.com/hajimehoshi/wasmserve/example
```

generates this error 
![image](https://user-images.githubusercontent.com/438252/236053744-be4dfd5a-ddd9-4635-8a60-babb0b18b7cf.png)

**Comment by hajimehoshi** [comment]
I think your evnrionment variables are too many in your environment for Go/Wasm. See the discussion at https://github.com/agnivade/wasmbrowsertest/issues/40

You can use `cleanenv` https://pkg.go.dev/github.com/agnivade/wasmbrowsertest/cmd/cleanenv

As this is not an issue in wasmserve itself, let me close this.
