### ISSUE TITLE
Fail to execute wasm_exec.js because of wrong MIME type

### ISSUE THREAD

**Issue by bukind** [hajimehoshi/wasmserve#35]
This is what I see in Chrome console:
```
GET http://localhost:8080/wasm_exec.js net::ERR_ABORTED 500 (Internal Server Error)Understand this error
localhost/:1
Refused to execute script from 'http://localhost:8080/wasm_exec.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.Understand this error
(index):12
Uncaught (in promise) ReferenceError: Go is not defined
    at (index):12:16
```

Chrome version is Version 127.0.6533.114 (Official Build) (64-bit)

**Comment by hajimehoshi** [comment]
That's odd. I failed to reproduce your issue.

![image](https://github.com/user-attachments/assets/649c0105-6c60-48ce-a3ab-488a173df945)

**Comment by hajimehoshi** [comment]
> net::ERR_ABORTED 500 (Internal Server Error)Understand this error

Where did this come from?

**Comment by bukind** [comment]
Maybe it is because my client is on Chromebook?  Here is what I see 
![Screenshot 2024-08-24 21 38 40](https://github.com/user-attachments/assets/eaa9e164-fed4-4267-809f-ec88234a8074)

**Comment by bukind** [comment]
Ah, I see that I don't have wasm_exec.js at $(GOROOT)/misc/wasm/.  My server OS is Rocky Linux 8.  I think I should install additional package(s).

**Comment by bukind** [comment]
Ok, so it is in `golang-misc` package from the appstream repo.  I guess it could be this way for all RHEL based distros.

**Comment by hajimehoshi** [comment]
Even if `wasm_exec.js` does not exist, wasmserve tries to get this from the repository. https://github.com/hajimehoshi/wasmserve/blob/a2f9d4ea4bc1095d3e4350c36f68775c459dbb89/main.go#L170-L181

**Comment by bukind** [comment]
Now I cannot test what error would be printed if there is no wasm_exec.js.  Even that I erased the package `golang-misc`, the program still works.  It is possible that it is cached somewhere.

**Comment by hajimehoshi** [comment]
Let me know if the issue happens again.
