### ISSUE TITLE
FR: Ability to inject custom JS module

### ISSUE THREAD

**Issue by LoparPanda** [hajimehoshi/wasmserve#36]
I was experimenting with WASM bindings and wanted to add a custom JS file in addition to `wasm_exec.js`. Although wasmserve can statically serve another JS file, it won't currently be loaded via the built-in `index.html` .

I hacked in a string flag into my own build which serves my purposes well enough. If the flag is set it injects a `<script>` tag for the file after `wasm_exec.js` is loaded. It also serves it at the root so keeping the JS file in an arbitrary relative location is possible. I thought if you think it's a useful feature that you probably have a cleaner way to set it up, either via flags or some type of configuration file.

**Comment by hajimehoshi** [comment]
You can put your own `index.html` and other files at the working directory and `wasmserve` would provide them instead of its embedded `index.html` and other files. Would this work?

**Comment by LoparPanda** [comment]
Yeah, I think that would work! It might be convenient if that was documented or if the shell `index.html` was also in the repo for others, but definitely very easy to copy the default served index and modify it.

**Comment by hajimehoshi** [comment]
The embedded `index.html` is a little special since arguments and environment variables are injected. We might want an API to return arguments and environment variables as JSON.

FYI, your HTML file doesn't have to be `index.html`. For example, `game.html` at the working directory is also served as it is.
