### ISSUE TITLE
NixOS and environment variables exceeds limit

### ISSUE THREAD

**Issue by dimkauzh** [hajimehoshi/wasmserve#37]
Hey! Awesome project! I have been using it on a lot of platforms, and I have ran into this error only on NixOS. the error is the following:
```
Uncaught (in promise) Error: total length of command line and environment variables exceeds limit
    run http://localhost:8080/wasm_exec.js:531
    <anonymous> http://localhost:8080/:16
    async* http://localhost:8080/:23
```
I have the feeling this is due to NixOS relying heavily on paths, which makes everything end up to this error. So my question would be: How can I fix it?
I just need it to work, in the end I will deploy on a clean Debian server. 
P.S. I tested the exact same codebase on a different machine and it seemed to work without that error.

**Comment by hajimehoshi** [comment]
See your environment variables by `env` and try to filter unnecessary ones.

**Comment by kirillrdy** [comment]
@dimkauzh also if you use your own index.html you can skip `go.env = `

**Comment by dimkauzh** [comment]
@kirillrdy @hajimehoshi With a clean environment and only some Go variables it seems to work fine. Thanks!

Here's how I did it (for anyone searching for the answer):
```bash
env -i \
  GOARCH="$GOARCH" \
  GOPATH="$GOPATH" \
  GOROOT="$GOROOT" \
  GOCACHE="$GOCACHE" \
  USER="$USER" \
  XDG_CACHE_HOME="$XDG_CACHE_HOME" \
  HOME="$HOME" \
  PATH="$GOPATH/bin:$PATH" \
  "$GOPATH/bin/wasmserve" ./test/backend
```

**Comment by dimkauzh** [comment]
Closing this issue as resolved
