### ISSUE TITLE
wasmserve: command not found

### ISSUE THREAD

**Issue by Zireael07** [hajimehoshi/wasmserve#9]
On Manjaro, after running go get ..., I get the above. I can kinda-sorta get around it by cd'ing to the folder wasmserve binary is in (GOPATH/bin), but then it complains it can't find main module for my project, which obviously isn't true (the project compiles fine otherwise)

**Comment by hajimehoshi** [comment]
Does your `$PATH` include `$GOPATH/bin`?

**Comment by Zireael07** [comment]
Hm, will check. Does wasmserve want relative path or absolute (to my project), by the way?

**Comment by hajimehoshi** [comment]
Both should work fine.

If you are using Go modules (`GO111MODULE=on` or `GO111MODULE=auto` with `go.mod`), the path obeys the current `go.mod`.

If you are not using Go modules (`GO111MODULE=off`), an absolute path indicates a project in `$GOPATH/src`.

**Comment by hajimehoshi** [comment]
The easiest way is to change your working directory to your project and run `wasmserve .`

**Comment by Zireael07** [comment]
Turns out I was missing $GOPATH/bin in $PATH (seriously, Rust and Python can add everything they want/need to PATH, Golang still can't?), but wasmserve . still complains about not being able to find main module. I thought it didn't use modules if we are in $GOPATH?

**Comment by hajimehoshi** [comment]
> (seriously, Rust and Python can add everything they want/need to PATH, Golang still can't?)

Go's installation in a separate directory also make sense, since this doesn't taint existing directories.

>  still complains about not being able to find main module

Is your project a main module btw?

> I thought it didn't use modules if we are in $GOPATH?

This depends on `GO111MODULE` value and the existence of `go.mod`. See also https://github.com/golang/go/wiki/Modules

**Comment by Zireael07** [comment]
The project only has one file, marked as package main at the top. Currently fiddling with go mod init, so far no dice...

**Comment by hajimehoshi** [comment]
Sorry I'll go to bed soon then I'll reply tomorrow. Could you show me the current error message?

**Comment by Zireael07** [comment]
Finally managed to make it work, go mod init roguelike/main made it work (the Go docs neglected to say the part after the slash had to match the package name...).

Looks like it works, I'll have to rearrange the files a bit for WASM to work because it the compiled WASM can't find resources above the src folder ("../fonts/terminal_16_16.png"), but the issue as such can be closed :) Thanks for your patience - I suppose for any future clueless users, the docs should mention 1) checking for GOPATH in PATH and 2) by default, in most Go installs nowadays, modules are in use.
